title: encerrado en casa
email: mark@matienzo.org
description: an attempt at organizing live experimental music and video art in the age of social distancing
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://encerradoen.casa" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:month/:day/:title/

sass:
  load_paths:
    - _sass

# Build settings
remote_theme: samesies/barber-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap


nav_pages:
  - about.markdown

## barber-jekyll

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts:
      - 'tag.html'
    title: 'encerrado en casa'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

google_analytics: UA-6399155-6

# MailChimp settings
mailchimp_action: https://casa.us19.list-manage.com/subscribe/post?u=86e8fc6b93ce5dadc646463eb&amp;id=981cd4c0b6
mailchimp_input: b_86e8fc6b93ce5dadc646463eb_981cd4c0b6

# Author settings
author:
  - name: Mark A. Matienzo
    bio: Based in the Bay Area, Mark A. Matienzo is an archivist and technologist, and performs music as Black Tent.
    url: https://matienzo.org/

formcarry: https://formcarry.com/s/wBL60ZAfcJAw
contact_img: /assets/images/wires.jpg
default_img: /assets/images/hand.jpg

social:
  - name: twitter
    url: https://twitter.com/anarchivist
  - name: instagram
    url: https://www.instagram.com/anarchivist/
  - name: facebook
    url: https://www.facebook.com/blacktentsound/
  - name: bandcamp
    url: https://blacktent.bandcamp.com/
  - name: soundcloud
    url: https://soundcloud.com/blacktentsound

compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
